repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/omnilib/ufmt
    rev: v2.2.0
    hooks:
    -   id: ufmt

-   repo: https://github.com/hadialqattan/pycln
    rev: v2.3.0
    hooks:
    - id: pycln
